# Generated by Django 4.2.13 on 2024-07-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
